plugins:
  - import
  - jest
  - prettier

env:
  es2021: true
  node: true

extends:
  - airbnb-base
  - prettier
  - plugin:import/recommended
  - plugin:jest/recommended

parserOptions:
  ecmaVersion: 12
  sourceType: module

rules:
  prettier/prettier: "error"
  import/extensions: ["error", "never", { "js": "always" }]
  no-console: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
